version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.0
  node: circleci/node@4.3.0
jobs:
   build_and_deploy:
     docker:
        - image: cimg/node:14.16.1
     steps:
       - checkout
       - aws-cli/setup
       - run: sudo npm i -g serverless npm@latest
       - run: npm install
       - run: sls deploy 
workflows:
  sqs-lambda-flow:
    jobs:
      - build_and_deploy